### PR TITLE
Add support for textarea rows

### PR DESCRIPTION
**Pull request by kevintraver**

### CODE REVIEW

**Comment by kevintraver** [comment]
There should probably be a seperate test for `textarea`.

**Comment by shuriu** [comment]
Hey @kevintraver, thanks for the PR! 👍 

I think you're right, there should definitely be a separate assertion for attributes specific to `textarea`. Also, I realised there are some `textarea` specific attributes that I forgot to add initially and are missing while [looking through the docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea). Specifically `cols`, `wrap` (plus `rows` which you added). As well as the `form` attribute which is not specific only to `textarea` but good to have.

In any case you could add a new render call at the end of that testcase and move the `it sets the rows attribute` assertion after and it should be perfect.

```js
this.render(hbs`{{do-control 'textarea' multiple=multiple}}`);
// assert `it sets the rows attribute`
```

And maybe you can add the missing ones as well and I'll merge after?

**Comment by shuriu** [comment]
Hey, I think I'll add this as is. The reason is that I have some other changes planned for a release that I intend to do shortly.

**Comment by kevintraver** [comment]
Ok thanks! We can work on a separate PR for textarea tests.

**Comment by shuriu** [comment]
I've already done this in #7 but I just haven't pushed the code. Incoming!

**Pull request merged**
